### ISSUE TITLE
ExpoLocalization error

### ISSUE THREAD

**Issue by kashee-lv** [PostHog/posthog-react-native#69]
Hi,

After upgrading posthog ^1.1.5 to "^2.1.1" this version i am facing this issue:
Error: Cannot find native module 'ExpoLocalization'

Even i try to install `npm i expo-localization`, but still same error

My react and react-native version
"react": "17.0.2",
"react-native": "0.68.0",

**Comment by gcho91** [comment]
I am also having the same issue

**Comment by gcho91** [comment]
Update: installing expo modules solved the problem! Just run `npx install-expo-modules@latest`

Reference: https://docs.expo.dev/bare/installing-expo-modules/#automatic-installation

> In order to use Expo modules in your app, you will need to install and configure the expo package.

**Comment by gcho91** [comment]
> Hi,
> 
> After upgrading posthog ^1.1.5 to "^2.1.1" this version i am facing this issue: Error: Cannot find native module 'ExpoLocalization'
> 
> Even i try to install `npm i expo-localization`, but still same error
> 
> My react and react-native version "react": "17.0.2", "react-native": "0.68.0",

Update: installing expo modules solved the problem! Just run npx install-expo-modules@latest

Reference: https://docs.expo.dev/bare/installing-expo-modules/#automatic-installation

In order to use Expo modules in your app, you will need to install and configure the expo package.

**Comment by SchlagerKhan** [comment]
For people, like me, who have no option/don't want to to implement expo in any fashion - I looked at the [source code](https://github.com/PostHog/posthog-js-lite/issues/30) and talked to community support who told me that vanilla ReactNative is not supported.

However, there is some light. 

1. [This issue](https://github.com/PostHog/posthog-js-lite/issues/30) exists that hopefully soon will support vanilla.
2. After some tinkering I successfully mocked all expo modules with the libraries mentioned in the issue above. This is possible since the only thing expo provides are some constants. <br/> <br/> I did this my using a babel alias plugin which replaces the libraries: `expo-application`, `expo-device`, `expo-localization` and `expo-file-system`.

**Comment by benjackwhite** [comment]
Hey there 👋 as of v2.2.0 expo modules are no longer required. Check out [the docs](https://posthog.com/docs/integrate/client/react-native) to see the installation instructions for non-expo projects. 

NOTE: The initialisation of PostHog has slightly changed so be sure to check that out. (The old way still works but may have some race condition issues).
