### ISSUE TITLE
Couldn't find a navigation object 

### ISSUE THREAD

**Issue by trobbertze** [PostHog/posthog-react-native#73]
Hi

I am currently evaluating Posthog for a React Native app.

I am getting the same error as logged in this issue:

https://github.com/PostHog/posthog/issues/11880

What I have found is that in our app the NavigationContainer is not the highest order component (if I can call it that). It is wrapped in a SafeAreaProvider, SafeAreaView and SideMenu components.

If I remove these components and make the NavigationContainer the highest order component, then I do not get the error.  But unfortunately my app requires those.

So my question is this, is it possible to have Posthog working when the NavigationContainer is not the highest order component?

**Comment by benjackwhite** [comment]
Hard to say anything for sure without much more context (React Native is a world of exceptions so code examples, reproduce-able snippets would be greatly appreciated).

The only thing that should be necessary for the navigation based tracking is for you to have the Provider _below_ the NavigationContainer ([see docs](https://posthog.com/docs/libraries/react-native#autocapture))

The key bit is in [this code](https://github.com/PostHog/posthog-js-lite/blob/master/posthog-react-native/src/hooks/useNavigationTracker.ts) that hooks into the navigation state. We use the `useNavigation` hook to get the state of the navigator in order to react to route changes, hence it needs to be below the provider.

You can of course just disable the auto tracking on the `PostHogProvider` and run the hook yourself in some component below the NavigationContainer. Something like:
```tsx
<PostHogProvider autocapture={{ captureScreens: false }}>
  <NavigationContainer>
  
  </NavigationContainer> 
</PostHogProvider>
```

**Comment by benjackwhite** [comment]
Moved to https://github.com/PostHog/posthog-js-lite/issues/101
